# Site settings
title: Your soundblog
email: your-email@domain.com
description: "Your soundblog description"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5

admin:
  github_username: vicox
  github_repo: soundblog
  soundcloud_client_id: 0686300807bd25cd798c519f70192c31
